@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class customer {
   bank_account: varchar(255)
   bank_code: varchar(255)
   birth_date: timestamp(6)
   city: varchar(255)
   country: varchar(255)
   currency: varchar(255)
   deleted: boolean
   dic: varchar(255)
   email: varchar(255)
   house_number: varchar(255)
   ico: varchar(255)
   name: varchar(255)
   phone_number: varchar(255)
   street: varchar(255)
   surname: varchar(255)
   trade_name: varchar(255)
   zip: varchar(255)
   id: bigint
}
class supplier {
   bank_account: varchar(255)
   bank_code: varchar(255)
   city: varchar(255)
   country: varchar(255)
   currency: varchar(255)
   dic: varchar(255)
   email: varchar(255)
   house_number: varchar(255)
   ico: varchar(255)
   phone_number: varchar(255)
   street: varchar(255)
   trade_name: varchar(255)
   zip: varchar(255)
   id: bigint
}

@enduml
